# Generated by Django 2.2.1 on 2019-05-02 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('match_type', models.CharField(max_length=50, null=True)),
                ('competition', models.CharField(max_length=50, null=True)),
                ('winner', models.CharField(max_length=50, null=True)),
                ('mom', models.CharField(max_length=50, null=True)),
                ('win_wickets', models.IntegerField(null=True)),
                ('win_run', models.IntegerField(null=True)),
                ('toss_win', models.CharField(max_length=100, null=True)),
                ('decision', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over', models.FloatField(default=None)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('striker', models.CharField(max_length=100)),
                ('non_striker', models.CharField(max_length=100)),
                ('bowler', models.CharField(max_length=100)),
                ('team', models.CharField(default=None, max_length=100)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Matches')),
            ],
        ),
    ]
